arch: trm
data_paths: ["data/sudoku-extreme-1k-aug-1000"]
evaluators: []
epochs: 50000
eval_interval: 5000
lr: 1e-4
puzzle_emb_lr: 1e-4
weight_decay: 1.0
puzzle_emb_weight_decay: 1.0
arch.mlp_t: true
arch.pos_encodings: none
arch.L_layers: 2
arch.H_cycles: 3
arch.L_cycles: 6
ema: true
